// [MF-4 = LDB-G11] design/layout-db/21-formats.md §2.4/§4: "Explicit
// format. Every route that returns or changes a payload answers `400
// format_required` without one; no route has a default." The plan asks
// for a GENERATED matrix "enumerated from the router table... one row per
// route x {format missing, stored and present, stored but absent on this
// layout, output (mana2/1), unregistered}". The three routes below are
// exactly the ones `src/routes/layouts.ts` gates on `parseFormatRequired`
// (`/v1/layouts`, `/v1/layouts/:ref`, `/v1/layouts/:ref/rev/:n` --
// `/history`'s `?format=` is a documented, deliberate exception, D4's own
// carve-out, and is NOT part of this matrix). The five scenario columns
// are generated by pairing each route with one shared `SCENARIOS` array
// rather than five hand-duplicated `it()` blocks per route, so a route
// added later to `ROUTES` automatically gets every scenario.
//
// "stored but absent on this layout" uses `tests/formats/stub-lineage.ts`'s
// `T1` (`t/1`, role: "stored") registered for this file only: a real
// second stored lineage the seeded layout never writes, exactly the
// "test-only second stored lineage" the plan's F2 scope calls for.
import { env } from "cloudflare:test";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Bindings } from "../../src/env";
import { commitWrite, type CommitInput } from "../../src/core/events";
import { fixedClock } from "../../src/core/time";
import { ulid } from "ulidx";
import { writeFetch } from "./write-support";
import { registerForTest } from "../../formats/registry.ts";
import { T1 } from "../formats/stub-lineage.ts";

const db = (env as unknown as Bindings).DB;
const clock = fixedClock("2026-07-17T00:00:00.000Z");
const OWNER = "owner-mf4-matrix";

let uniqueCounter = 0;
function uniqueName(prefix: string): string {
  return `${prefix}-${uniqueCounter++}`;
}

async function seed(): Promise<string> {
  const input: CommitInput = {
    layoutId: ulid(),
    creating: true,
    currentN: 0,
    currentLayout: null,
    currentFormats: new Map(),
    layout: { kind: "created", name: uniqueName("mf4"), owner: OWNER, created_at: clock(), deleted: false },
    format: { kind: "format_added", lineage: "spark", format: "spark/1", payload: { keys: {} }, hasMagic: false },
    modified_at: clock(),
    actor: OWNER,
    via: "discord",
    source: { client: "discord-app:test", version: null },
    upstream: null,
  };
  const { layout } = await commitWrite(db, clock, input);
  return layout.id;
}

// route descriptors: `path(id, format)` builds the URL, `?format=`
// appended only when `format !== undefined` (so the "missing" scenario is
// expressed the same way for every route: just omit it).
interface RouteDesc {
  name: string;
  path(id: string, format: string | undefined): string;
}
const ROUTES: RouteDesc[] = [
  { name: "GET /v1/layouts (list)", path: (id, f) => `/v1/layouts?owner=${OWNER}${f !== undefined ? `&format=${f}` : ""}` },
  { name: "GET /v1/layouts/:ref", path: (id, f) => `/v1/layouts/${id}${f !== undefined ? `?format=${f}` : ""}` },
  { name: "GET /v1/layouts/:ref/rev/:n", path: (id, f) => `/v1/layouts/${id}/rev/1${f !== undefined ? `?format=${f}` : ""}` },
];

type StatusExp = { status: number; error?: string };
type ListExp = StatusExp | "present" | "absent-from-list";

interface Scenario {
  name: string;
  format: string | undefined;
  detail: StatusExp;
  // GET .../rev/:n is narrower than GET :ref (§2.4): revs are numbered
  // per (layout, lineage), so an output format is refused outright
  // (bad_request, not derived) and "never stored on this layout" reads as
  // a plain not_found (no rev N exists) rather than the detail route's
  // dedicated format_absent -- the plan's §2.4 text only spells out
  // format_absent for the detail route, not for rev. Defaults to
  // `detail` when a scenario doesn't need to differ.
  rev?: StatusExp;
  list: ListExp;
}

const SCENARIOS: Scenario[] = [
  { name: "format missing", format: undefined, detail: { status: 400, error: "format_required" }, list: { status: 400, error: "format_required" } },
  { name: "stored and present (spark/1)", format: "spark/1", detail: { status: 200 }, list: "present" },
  {
    name: "stored but absent on this layout (t/1)",
    format: "t/1",
    detail: { status: 404, error: "format_absent" },
    rev: { status: 404, error: "not_found" },
    list: "absent-from-list",
  },
  {
    name: "output, derivable (mana2/1)",
    format: "mana2/1",
    detail: { status: 200 },
    rev: { status: 400, error: "bad_request" },
    list: "present",
  },
  { name: "unregistered (cmini/1)", format: "cmini/1", detail: { status: 400, error: "unknown_format" }, list: { status: 400, error: "unknown_format" } },
];

describe("[MF-4 = LDB-G11] format_required matrix: every format-bearing GET route x every format scenario", () => {
  // registerForTest per-file, unregistered in afterAll -- same convention
  // `tests/api/held.test.ts`'s HELD_FORMAT and `tests/formats/path.test.ts`'s
  // stub lineage already use.
  let unregisterT1: () => void;
  beforeAll(() => {
    unregisterT1 = registerForTest(T1);
  });
  afterAll(() => {
    unregisterT1();
  });

  for (const route of ROUTES) {
    const isList = route.name.includes("(list)");
    const isRev = route.name.includes("/rev/:n");
    for (const scenario of SCENARIOS) {
      it(`[MF-4] [LDB-G11] ${route.name} x ${scenario.name}`, async () => {
        const id = await seed();
        const res = await writeFetch(route.path(id, scenario.format), "GET");

        if (isList) {
          if (scenario.list === "present" || scenario.list === "absent-from-list") {
            expect(res.status).toBe(200);
            const body = await res.json<{ items: { id: string }[] }>();
            const found = body.items.some((i) => i.id === id);
            expect(found).toBe(scenario.list === "present");
          } else {
            expect(res.status).toBe(scenario.list.status);
            if (scenario.list.error !== undefined) {
              await expect(res.json()).resolves.toMatchObject({ error: scenario.list.error });
            }
          }
          return;
        }

        const exp = isRev ? (scenario.rev ?? scenario.detail) : scenario.detail;
        expect(res.status).toBe(exp.status);
        if (exp.error !== undefined) {
          await expect(res.json()).resolves.toMatchObject({ error: exp.error });
        }
      });
    }
  }
});
