// [MF-4 = LDB-G11] design/layout-db/21-formats.md §2.4/§4: "Explicit
// format. Every route that returns or changes a payload answers `400
// format_required` without one; no route has a default." The plan asks
// for a GENERATED matrix "enumerated from the router table... one row per
// route x {format missing, stored and present, stored but absent on this
// layout, output (mana2/1), unregistered}". The three routes below are
// exactly the ones `src/routes/layouts.ts` gates on `parseFormatRequired`
// (`/v1/layouts`, `/v1/layouts/:ref`, `/v1/layouts/:ref/rev/:n` --
// `/history`'s `?format=` is a documented, deliberate exception, D4's own
// carve-out, and is NOT part of this matrix). The five scenario columns
// are generated by pairing each route with one shared `SCENARIOS` array
// rather than five hand-duplicated `it()` blocks per route, so a route
// added later to `ROUTES` automatically gets every scenario.
//
// "stored but absent on this layout" uses `tests/formats/stub-lineage.ts`'s
// `T1` (`t/1`, role: "stored") registered for this file only: a real
// second stored lineage the seeded layout never writes, exactly the
// "test-only second stored lineage" the plan's F2 scope calls for.
import { env } from "cloudflare:test";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Bindings } from "../../src/env";
import { commitWrite, type CommitInput } from "../../src/core/events";
import { fixedClock } from "../../src/core/time";
import { ulid } from "ulidx";
import { app } from "../../src/index";
import { actorFixture, register, writeFetch } from "./write-support";
import { registerForTest } from "../../formats/registry.ts";
import { T1 } from "../formats/stub-lineage.ts";

const db = (env as unknown as Bindings).DB;
const clock = fixedClock("2026-07-17T00:00:00.000Z");
const OWNER = "owner-mf4-matrix";

let uniqueCounter = 0;
function uniqueName(prefix: string): string {
  return `${prefix}-${uniqueCounter++}`;
}

async function seed(): Promise<string> {
  const input: CommitInput = {
    layoutId: ulid(),
    creating: true,
    currentN: 0,
    currentLayout: null,
    currentFormats: new Map(),
    layout: { kind: "created", name: uniqueName("mf4"), owner: OWNER, created_at: clock(), deleted: false },
    format: { kind: "format_added", lineage: "spark", format: "spark/1", payload: { keys: {} }, hasMagic: false },
    modified_at: clock(),
    actor: OWNER,
    via: "discord",
    source: { client: "discord-app:test", version: null },
    upstream: null,
  };
  const { layout } = await commitWrite(db, clock, input);
  return layout.id;
}

// route descriptors: `path(id, format)` builds the URL, `?format=`
// appended only when `format !== undefined` (so the "missing" scenario is
// expressed the same way for every route: just omit it).
interface RouteDesc {
  name: string;
  path(id: string, format: string | undefined): string;
}
const ROUTES: RouteDesc[] = [
  { name: "GET /v1/layouts (list)", path: (id, f) => `/v1/layouts?owner=${OWNER}${f !== undefined ? `&format=${f}` : ""}` },
  { name: "GET /v1/layouts/:ref", path: (id, f) => `/v1/layouts/${id}${f !== undefined ? `?format=${f}` : ""}` },
  { name: "GET /v1/layouts/:ref/rev/:n", path: (id, f) => `/v1/layouts/${id}/rev/1${f !== undefined ? `?format=${f}` : ""}` },
];

// Coordinator review (third batch, MEDIUM): "M4 is only half done... Build
// both lists FROM app.routes... Make the test FAIL when a registered
// route has no matrix entry, so a new route can't slip past." The earlier
// `routerHas` only checked that a hand-picked handful of routes still
// exist -- it said nothing about a route ADDED to the router with no
// corresponding matrix entry. This enumerates every `/v1/layouts*` route
// the live router actually has and requires each one to be classified:
// either it names its own format requirement (the GET matrix's `ROUTES`,
// or a write route below expecting `format_required`), or it's in
// `EXEMPT_ROUTES` with a stated reason. A route in neither list fails
// this test, loudly, by name.
const ALL_LAYOUTS_ROUTES = app.routes.filter((r) => r.path === "/v1/layouts" || r.path.startsWith("/v1/layouts/"));

interface ExemptRoute {
  method: string;
  path: string;
  reason: string;
}
// Every `/v1/layouts*` route that concerns no format at all, or where
// `?format=` is a documented, non-required exception (D4's own carve-out
// for `/history`) -- each reason is the SAME one 21-formats.md §2.4/D4
// gives, and each of these routes has its own dedicated coverage
// elsewhere (never "exempt" meaning "untested").
const EXEMPT_ROUTES: ExemptRoute[] = [
  { method: "GET", path: "/v1/layouts/:ref/likes", reason: "a like list concerns no format at all" },
  { method: "GET", path: "/v1/layouts/:ref/history", reason: "D4's own documented carve-out: ?format= is an optional FILTER here (absent means every event), never a default" },
  { method: "PUT", path: "/v1/layouts/:ref/like", reason: "D13 L3: a like needs no version and concerns no format" },
  { method: "DELETE", path: "/v1/layouts/:ref/like", reason: "D13 L3: an unlike needs no version and concerns no format" },
  { method: "DELETE", path: "/v1/layouts/:ref", reason: "delete is layout-scope only (name/owner/deletion); it concerns no format" },
  { method: "POST", path: "/v1/layouts/:ref/restore", reason: "restore is layout-scope only; it concerns no format" },
  { method: "POST", path: "/v1/layouts/:ref/transfer", reason: "transfer is layout-scope only; it concerns no format" },
];

// Write routes whose BODY names a format and must answer `400
// format_required` without one (this file's own write-body describe
// block below exercises each). PATCH is included even though a `{name}`
// PATCH (layout scope) needs none -- `checkBody`'s ajv schema requires
// `format` only for PATCH bodies that also name an edit key
// (`classifyPatch`), which is exactly what the PATCH case below tests.
const FORMAT_REQUIRED_WRITE_ROUTES: { method: string; path: string }[] = [
  { method: "POST", path: "/v1/layouts" },
  { method: "PUT", path: "/v1/layouts/:ref" },
  { method: "PATCH", path: "/v1/layouts/:ref" },
];

// The GET matrix's own `ROUTES` (below) are keyed by name + a path
// BUILDER (they need a real id/format substituted in), not a bare
// (method, path) pair -- restated here as plain router coordinates so
// this classification list is a flat, checkable set.
const FORMAT_REQUIRED_GET_ROUTES: { method: string; path: string }[] = [
  { method: "GET", path: "/v1/layouts" },
  { method: "GET", path: "/v1/layouts/:ref" },
  { method: "GET", path: "/v1/layouts/:ref/rev/:n" },
];

it("[MF-4] [LDB-G11] every /v1/layouts* route the router has is classified here: format-required, or exempt with a stated reason", () => {
  expect(ALL_LAYOUTS_ROUTES.length).toBeGreaterThan(0);
  const classified = new Set([...FORMAT_REQUIRED_GET_ROUTES, ...FORMAT_REQUIRED_WRITE_ROUTES, ...EXEMPT_ROUTES].map((r) => `${r.method} ${r.path}`));
  const unclassified = ALL_LAYOUTS_ROUTES.filter((r) => !classified.has(`${r.method} ${r.path}`)).map((r) => `${r.method} ${r.path}`);
  expect(unclassified, "a route was added to the router with no format-requirement classification in this file").toEqual([]);
});

type StatusExp = { status: number; error?: string };
type ListExp = StatusExp | "present" | "absent-from-list";

interface Scenario {
  name: string;
  format: string | undefined;
  detail: StatusExp;
  // GET .../rev/:n is narrower than GET :ref for OUTPUT formats only
  // (§2.4): revs are numbered per (layout, lineage), and a derived format
  // never has one, so `mana2/1` is refused outright (bad_request, not
  // derived) rather than served. For "never stored on this layout",
  // though, `/rev/:n` uses the SAME `format_absent` vocabulary the detail
  // route does (coordinator review, 2026-09-11): the layout plainly
  // doesn't have that lineage at all, which is exactly what
  // `format_absent` means everywhere else it's thrown -- only a genuinely
  // out-of-range rev NUMBER on a lineage the layout DOES have falls
  // through to a plain `not_found` (`tests/api/history.test.ts`'s own
  // LDB-R5 case covers that one). Defaults to `detail` when a scenario
  // doesn't need to differ.
  rev?: StatusExp;
  list: ListExp;
}

const SCENARIOS: Scenario[] = [
  { name: "format missing", format: undefined, detail: { status: 400, error: "format_required" }, list: { status: 400, error: "format_required" } },
  { name: "stored and present (spark/1)", format: "spark/1", detail: { status: 200 }, list: "present" },
  {
    name: "stored but absent on this layout (t/1)",
    format: "t/1",
    detail: { status: 404, error: "format_absent" },
    rev: { status: 404, error: "format_absent" },
    list: "absent-from-list",
  },
  {
    name: "output, derivable (mana2/1)",
    format: "mana2/1",
    detail: { status: 200 },
    rev: { status: 400, error: "bad_request" },
    list: "present",
  },
  { name: "unregistered (cmini/1)", format: "cmini/1", detail: { status: 400, error: "unknown_format" }, list: { status: 400, error: "unknown_format" } },
];

describe("[MF-4 = LDB-G11] format_required matrix: every format-bearing GET route x every format scenario", () => {
  // registerForTest per-file, unregistered in afterAll -- same convention
  // `tests/api/held.test.ts`'s HELD_FORMAT and `tests/formats/path.test.ts`'s
  // stub lineage already use.
  let unregisterT1: () => void;
  beforeAll(() => {
    unregisterT1 = registerForTest(T1);
  });
  afterAll(() => {
    unregisterT1();
  });

  for (const route of ROUTES) {
    const isList = route.name.includes("(list)");
    const isRev = route.name.includes("/rev/:n");
    for (const scenario of SCENARIOS) {
      it(`[MF-4] [LDB-G11] ${route.name} x ${scenario.name}`, async () => {
        const id = await seed();
        const res = await writeFetch(route.path(id, scenario.format), "GET");

        if (isList) {
          if (scenario.list === "present" || scenario.list === "absent-from-list") {
            expect(res.status).toBe(200);
            const body = await res.json<{ items: { id: string }[] }>();
            const found = body.items.some((i) => i.id === id);
            expect(found).toBe(scenario.list === "present");
          } else {
            expect(res.status).toBe(scenario.list.status);
            if (scenario.list.error !== undefined) {
              await expect(res.json()).resolves.toMatchObject({ error: scenario.list.error });
            }
          }
          return;
        }

        const exp = isRev ? (scenario.rev ?? scenario.detail) : scenario.detail;
        expect(res.status).toBe(exp.status);
        if (exp.error !== undefined) {
          const body = await res.json<Record<string, unknown>>();
          expect(body).toMatchObject({ error: exp.error });
          // Coordinator review (H2): on a single-layout route,
          // format_required/format_absent carry the layout's own fields
          // and `formats` -- not just the bare error -- so a caller never
          // needs a second request to learn what it already asked about.
          if (exp.error === "format_required" || exp.error === "format_absent") {
            expect(body, `${route.name} x ${scenario.name}: ${exp.error} must carry layout fields`).toMatchObject({
              id,
              name: expect.any(String),
              layout_rev: expect.any(Number),
              formats: expect.any(Object),
            });
          }
        }
      });
    }
  }
});

// Coordinator review (M4, D4): "cover POST/PUT/PATCH bodies too" -- a
// write body missing `format` entirely answers the SAME dedicated
// `400 format_required` a read route does, never a generic `bad_request`
// naming `/format` as just another missing property (`src/routes/
// schemas.ts`'s `checkBody` used to do exactly that for POST/PUT before
// this fix).
describe("[MF-4] [LDB-G11] format_required on write bodies (POST, PUT, PATCH)", () => {
  function ownerHeaders(token: string) {
    const fake = actorFixture();
    return register(fake, token, OWNER);
  }

  it("[MF-4] [LDB-G11] POST /v1/layouts with no `format` -> 400 format_required", async () => {
    const headers = ownerHeaders(`tok-${uniqueName("post")}`);
    const res = await writeFetch("/v1/layouts", "POST", headers, { name: uniqueName("mf4-post"), payload: { keys: {} } });
    expect(res.status).toBe(400);
    await expect(res.json()).resolves.toMatchObject({ error: "format_required" });
  });

  it("[MF-4] [LDB-G11] PUT /v1/layouts/:ref with no `format` -> 400 format_required", async () => {
    const id = await seed();
    const headers = ownerHeaders(`tok-${uniqueName("put")}`);
    const res = await writeFetch(`/v1/layouts/${id}`, "PUT", { ...headers, "If-Match": "*" }, { payload: { keys: {} } });
    expect(res.status).toBe(400);
    await expect(res.json()).resolves.toMatchObject({ error: "format_required" });
  });

  it("[MF-4] [LDB-G11] PATCH /v1/layouts/:ref with an edit key but no `format` -> 400 format_required", async () => {
    const id = await seed();
    const headers = ownerHeaders(`tok-${uniqueName("patch")}`);
    const res = await writeFetch(`/v1/layouts/${id}`, "PATCH", { ...headers, "If-Match": "*" }, { fingermap: { a: "LM" } });
    expect(res.status).toBe(400);
    await expect(res.json()).resolves.toMatchObject({ error: "format_required" });
  });
});
