// COPY: sign-off pending
//
// Every user-facing string on akldb.org lives here (design/akldb-site/
// 01-plan.md §5, SITE-5: a string of 3+ words anywhere else under src/ is a
// build-time test failure). CLAUDE.md's copy rule ("never touch user-facing
// copy... without saltorbit's sign-off") applies to this whole file until the
// marker above is removed by saltorbit himself.

export const copy = {
  app: {
    pageError: "This page hit an error:",
    retry: "Try again",
  },
  siteName: "akldb",
  header: {
    tagline: "the community akldb",
    navHome: "Layouts",
    navChanges: "Event log", // saltorbit 2026-09-13 (was "Changes")
    navDocs: "Docs",
    navAdmin: "Moderation",
    signIn: "Sign in with Discord",
    signInUnavailable: "Sign-in is not configured yet",
    signOut: "Sign out",
    signedInAs: (name: string) => `Signed in as ${name}`,
  },
  home: {
    title: "Layouts", // signed off by saltorbit 2026-09-13 (was "Every layout in akldb")
    searchPlaceholder: "Search layout names",
    authorPlaceholder: "Filter by author id",
    sortLikes: "Most liked",
    sortModified: "Recently modified",
    sortName: "Name",
    magicAny: "Any",
    magicOnly: "Magic only",
    magicNone: "No magic",
    loading: "Loading every layout, this can take a moment",
    loadError: "Could not load the layout list from akldb",
    empty: "No layouts match this filter",
    countSuffix: (n: number) => `${n} layouts`,
    colName: "Name",
    colOwner: "Owner",
    colLikes: "Likes",
    colModified: "Modified",
  },
  layout: {
    backToHome: "Back to all layouts",
    notFound: "This layout does not exist, or has been deleted",
    loadError: "Could not load this layout from akldb",
    owner: "Owner",
    copyPayload: "Copy",
    copied: "Copied",
    likes: "Likes",
    created: "Created",
    modified: "Modified",
    formats: "Formats stored",
    linkLabel: "External link",
    noLink: "No external link on file",
    historyTitle: "History",
    historyEmpty: "No recorded events for this layout",
    historyLoadMore: "Load older events",
  },
  actions: {
    sectionTitle: "Manage this layout",
    like: "Like",
    unlike: "Unlike",
    rename: "Rename",
    renamePrompt: "New name",
    delete: "Delete",
    deletedNotice: "This layout has been deleted. Restoring brings it back under its previous name (or the one you choose below).",
    restore: "Restore",
    restoreNamePrompt: "Restore under a different name (optional)",
    transfer: "Transfer ownership",
    transferPrompt: "New owner's Discord id",
    linkSectionTitle: "External link",
    linkPrompt: "https://…",
    linkSubmit: "Submit link",
    linkSubmitAdmin: "Set link",
    linkClear: "Clear link",
    linkPending: (url: string) => `Pending review: ${url}`,
    linkQueued: "Submitted -- an admin will review this link",
    linkSetImmediately: "Link approved immediately (admin action)",
    confirm: "Confirm",
    cancel: "Cancel",
    staleNotice: "This record changed since it was loaded here",
    reload: "Reload",
    seqNotice: (seq: number) => `Recorded as event #${seq}`,
    signInToManage: "Sign in to like or manage this layout",
  },
  author: {
    title: (name: string) => `Layouts by ${name}`,
    notFound: "No author found for this id",
    loadError: "Could not load this author from akldb",
    empty: "This author has no layouts on record",
  },
  changes: {
    title: "Event log",
    loadError: "Could not load the change feed from akldb",
    empty: "Nothing has changed yet",
    loadMore: "Load older events",
    kindColumn: "Kind",
    scopeColumn: "Scope",
    scopeLayout: "layout",
    layoutColumn: "Layout",
    actorColumn: "Actor",
    whenColumn: "When",
    kinds: {
      "admin.user_banned": "User banned",
      "admin.user_unbanned": "User unbanned",
      "admin.likes_set": "Likes overridden",
      "admin.author_renamed": "Author renamed by admin",
      "admin.added": "Admin added",
      "admin.removed": "Admin removed",
      "admin.import_paused": "Import paused",
      "admin.import_resumed": "Import resumed",
      "admin.import_ticked": "Import run manually",
      "admin.diff_ticked": "Diff run manually",
      "admin.nightly_ticked": "Nightly job run manually",
      "admin.client_registered": "Bot client registered",
      "admin.client_revoked": "Bot client revoked",
      link_submitted: "Link submitted for review",
      link_approved: "Link approved",
      link_rejected: "Link rejected",
      link_cleared: "Link cleared",
    },
  },
  docs: {
    title: "Adopting the akldb API",
    loadError: "The API guide could not be rendered for this build",
    loading: "Loading the API guide",
    tocBrief: "Brief",
    tocAuth: "Auth & ownership",
    tocTrustedClients: "Trusted clients",
    tocGuide: "Adoption guide",
    tocErrors: "Errors",
    briefHeading: "API brief",
    baseUrlLabel: "Base URL",
    authLanesHeading: "Two ways to authenticate",
    laneUserName: "User lane",
    laneUserSummary: "A Discord OAuth bearer token, sent as Authorization: Bearer",
    laneClientName: "Client lane",
    laneClientSummary: "An Ed25519-signed request, asserting the Discord user it acts for",
    endpointsHeading: "Endpoints",
    groupRead: "Read",
    groupWrite: "Write",
    groupLikes: "Likes",
    groupLink: "Link",
    groupAdmin: "Admin",
    colMethod: "Method",
    colPath: "Path",
    colAuth: "Auth",
    colPurpose: "Purpose",
    colStatuses: "Statuses",
    ifMatchHeading: "If-Match scopes",
    ifMatchBody: 'A write against an existing record names the scope it edits: "layout:<rev>" for a layout-level write, or "<lineage>:<rev>" (for example "spark:7") for a format write.',
    idempotencyHeading: "Idempotency-Key",
    idempotencyBody: "An optional header on any mutating /v1/layouts* request: 1-128 printable ASCII characters, replayed verbatim on a retry with the same key, method, path and body.",
    rateLimitsHeading: "Rate limits",
    rateLimitsBody: "1000 writes per 10 minutes per actor; the client lane adds a further 5000 per 10 minutes per client id.",
    formatParamHeading: "?format= is required",
    formatParamBody: "Every route that returns a payload needs an explicit ?format= naming spark/1 or mana2/1 -- there is no default.",
    errorShapeHeading: "Error shape",
    errorShapeBody: 'Every error answers {"error": "<code>", "message": "<text>"}, plus any extra fields that error code carries.',
    errorTableLinkLabel: "Show the full error table in the guide below",
    moderationHeading: "Moderation",
    moderationBody: "An admin can ban a user, override an author's display name, and approve or reject a submitted link -- every action appends an event to the public feed.",
    copyButtonLabel: "Copy as Markdown",
    copyButtonCopied: "Copied to your clipboard",
    copyButtonFailed: "Could not use the clipboard -- select the text below and copy it",
    rawLinkLabel: "Open the raw file at /adoption.md",
    showGuideLabel: "Show the full guide",
    hideGuideLabel: "Hide the full guide",
    authDiagramHeading: "How auth and ownership work",
    authDiagramCaption: "A signed-in user proves identity once (cached up to five minutes); every write after that is checked against the record's own owner (or an admin) and its current revision before an event is appended.",
    authDiagramAriaLabel:
      "Sequence diagram: a browser or app signs in through Discord OAuth, exchanges the code for an access token, and calls GET /v1/me with that token as a bearer. akldb verifies the token with Discord's own oauth2 me endpoint, caching the answer up to five minutes, then reads admin and banned roles fresh on every request. A later write carries an If-Match header naming the record's current revision; akldb checks the caller is the record's owner or an admin before appending an event and answering, and the change feed at GET /v1/changes is the ground truth a client polls afterward.",
    trustedClientHeading: "How a trusted Discord client works",
    trustedClientCaption: "A registered client (an Ed25519 keypair, an admin-created row naming its capabilities) signs each request and asserts the Discord user it acts for -- the same write pipeline runs afterward, and a long-poll keeps it current without a timer.",
    trustedClientAriaLabel:
      "Sequence diagram: a registered client reads a Discord user id from an incoming message, signs a request with its own Ed25519 key over the method, path, timestamp, nonce, actor and body hash, and sends five X-Akl- headers to akldb. akldb verifies the signature against the client's stored public key, inserts the nonce as its own replay check, and confirms the client's capabilities allow acting as that user. The request then runs the same write pipeline a bearer-token write would, appending an event and answering 200 or 201. Afterward the client can long-poll GET /v1/changes with wait=25, which akldb holds open for any registered client, checking the event head about once a second, until new events exist or the wait elapses.",
  },
  admin: {
    title: "Moderation",
    notAdmin: "This page is only visible to akldb admins",
    tabLayouts: "Layouts",
    tabAuthors: "Authors",
    tabBans: "Bans",
    tabLinkQueue: "Link queue",
    tabAdmins: "Admins",
    tabImport: "Import",
    // UNSIGNED COPY (clients moderation, 2026-09-13) -- awaiting saltorbit
    tabClients: "Clients",
    layouts: {
      searchPlaceholder: "Layout name or id",
      searchButton: "Search",
      notFound: "No layout matches this name or id",
      loadError: "Could not load this layout from akldb",
    },
    authors: {
      lookupPlaceholder: "Discord user id",
      lookupButton: "Look up",
      notFound: "No author found for this id",
      loadError: "Could not load this author from akldb",
      currentName: (name: string) => `Current name: ${name}`,
      newNamePrompt: "New display name",
      rename: "Rename",
      renamed: "Name updated. Sign-ins and the cmini import will no longer overwrite it.",
    },
    bans: {
      loadError: "Could not load the ban list from akldb",
      empty: "No one is banned",
      colUser: "User",
      colBy: "Banned by",
      colAt: "Since",
      colReason: "Reason",
      userPlaceholder: "Discord user id",
      reasonPlaceholder: "Reason (optional)",
      banButton: "Ban",
      unbanButton: "Unban",
      cannotBanAdmin: "An admin cannot be banned",
    },
    linkQueue: {
      loadError: "Could not load the link queue from akldb",
      empty: "Nothing here",
      statusPending: "Pending",
      statusApproved: "Approved",
      statusRejected: "Rejected",
      statusSuperseded: "Superseded",
      colUrl: "URL",
      colLayout: "Layout",
      colSubmittedBy: "Submitted by",
      colSubmittedAt: "Submitted",
      colStatus: "Status",
      approve: "Approve",
      reject: "Reject",
      rejectReasonPrompt: "Reason (optional)",
    },
    admins: {
      loadError: "Could not load the admin list from akldb",
      empty: "No admins on record",
      colUser: "User",
      colAddedBy: "Added by",
      colAddedAt: "Since",
      colNote: "Note",
      userPlaceholder: "Discord user id",
      notePlaceholder: "Note (optional)",
      addButton: "Add admin",
      removeButton: "Remove",
      lastAdmin: "The last admin cannot be removed",
    },
    import: {
      pause: "Pause import",
      resume: "Resume import",
      tick: "Run import now",
      paused: "Import is paused",
      running: "Import is running",
      healthTitle: "Health",
      healthLoadError: "Could not load health from akldb",
    },
    // UNSIGNED COPY (clients moderation, 2026-09-13) -- awaiting saltorbit
    clients: {
      loadError: "Could not load the client list from akldb",
      empty: "No clients registered",
      colClient: "Client",
      colOwner: "Owner",
      colCaps: "Capabilities",
      colStatus: "Status",
      colSuspended: "Suspended",
      colRevoked: "Revoked",
      statusActive: "Active",
      statusSuspended: "Suspended",
      statusRevoked: "Revoked",
      suspendedAt: (at: string) => `Since ${at}`,
      suspendButton: "Suspend",
      reactivateButton: "Reactivate",
      revokeButton: "Revoke",
      revokeConfirmNotice: "This cannot be undone.",
      clientAlreadyRevoked: "This client is already revoked",
    },
  },
  notFound: {
    title: "Page not found",
    body: "There is nothing at this address",
    backHome: "Go back to the layout list",
  },
  common: {
    unknown: "unknown",
    yes: "yes",
    no: "no",
  },
} as const;
