#!/usr/bin/env node
// db/scripts/codeowners.mjs -- generates .github/CODEOWNERS from every
// db/formats/<name>/<major>/OWNERS file (12 §3 X5 item 4, LDB-G3, promised
// in 04 §2 -- "owners merge their own format" -- and unenforced until now).
// Each OWNERS file's non-comment, non-blank lines are GitHub handles (one
// or more per line, whitespace-separated); the generated line for a format
// directory is "<prefix>formats/<name>/<major>/ @handle1 @handle2 ..." --
// the prefix is "db/" inside this monorepo, "" once db/ is the repo root
// (repoLayout(), tests/tools/repo.ts) -- which, combined with GitHub's own
// "Require review from Code Owners" branch protection (X6 item 3), is what
// actually enforces "owners merge their own format".
//
// Usage:
//   node db/scripts/codeowners.mjs            # (re)writes .github/CODEOWNERS
//   node db/scripts/codeowners.mjs --check     # exits 1 if the committed
//                                               # file would change; writes
//                                               # nothing (db/tests/tools/
//                                               # codeowners.test.ts runs
//                                               # exactly this)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { repoLayout } from "../tests/tools/repo.ts";

const DB_ROOT = path.resolve(fileURLToPath(import.meta.url), "..", "..");
const FORMATS_ROOT = path.join(DB_ROOT, "formats");

// { name, major, ownersPath } for every db/formats/<name>/<major>/ that has
// its own OWNERS file -- sorted so the generated file (and its ordering) is
// deterministic across runs and machines.
export function formatDirs() {
  const dirs = [];
  for (const nameEnt of fs.readdirSync(FORMATS_ROOT, { withFileTypes: true })) {
    if (!nameEnt.isDirectory()) continue;
    const namePath = path.join(FORMATS_ROOT, nameEnt.name);
    for (const majorEnt of fs.readdirSync(namePath, { withFileTypes: true })) {
      if (!majorEnt.isDirectory()) continue;
      const ownersPath = path.join(namePath, majorEnt.name, "OWNERS");
      if (fs.existsSync(ownersPath)) {
        dirs.push({ name: nameEnt.name, major: majorEnt.name, ownersPath });
      }
    }
  }
  dirs.sort((a, b) => (a.name === b.name ? a.major.localeCompare(b.major) : a.name.localeCompare(b.name)));
  return dirs;
}

export function parseOwners(ownersPath) {
  const text = fs.readFileSync(ownersPath, "utf8");
  const handles = [];
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    for (const tok of trimmed.split(/\s+/)) {
      if (tok) handles.push(tok.startsWith("@") ? tok : `@${tok}`);
    }
  }
  if (handles.length === 0) {
    throw new Error(`${ownersPath}: no GitHub handles found (every non-comment line was blank)`);
  }
  return handles;
}

export function generate() {
  const { dbPrefix } = repoLayout();
  const lines = [
    "# GENERATED by db/scripts/codeowners.mjs -- do not hand-edit.",
    "# One line per format major, from db/formats/<name>/<major>/OWNERS",
    "# (design/layout-db/04-governance.md, LDB-G3).",
    "",
    ...formatDirs().map((d) => `${dbPrefix}formats/${d.name}/${d.major}/ ${parseOwners(d.ownersPath).join(" ")}`),
    "",
  ];
  return lines.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const { repoRoot } = repoLayout();
  const outPath = path.join(repoRoot, ".github", "CODEOWNERS");
  const generated = generate();

  if (check) {
    const committed = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
    if (committed !== generated) {
      console.error("[LDB-G3] .github/CODEOWNERS is stale -- run 'node db/scripts/codeowners.mjs' and commit the result.");
      process.exitCode = 1;
      return;
    }
    console.log("[LDB-G3] .github/CODEOWNERS is up to date.");
    return;
  }

  fs.writeFileSync(outPath, generated);
  console.log(`[LDB-G3] wrote ${outPath}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
